services:
  php:
    env_file: ./.env
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: pms-php
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "80:80"
