services:
  php:
    env_file: ./.env
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: pms-php
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 80:80

  vite:
    build:
      context: .
      dockerfile: docker/dockerfile
    command: bash -c "npm install && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5173:5173
    depends_on:
      - php
