FROM dunglas/frankenphp:1.3-php8.3.14

WORKDIR /app

RUN install-php-extensions pdo_mysql \
	gd \
	intl \
	zip \
	opcache \
    pcntl \
    redis

RUN curl --silent --show-error https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

COPY ./composer.* ./

RUN composer install --no-plugins --no-scripts \
    --no-dev \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader; \
    cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini;

WORKDIR /app

COPY ./.env.example /app/.env
COPY ./ /app/

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

RUN npm install && \
    npm run build

# Disable HTTP redirection
ENV SERVER_NAME=:80
ENV CADDY_GLOBAL_OPTIONS=debug

# Expose port 80
EXPOSE 80
EXPOSE 8081

CMD ["bash", "./docker/entrypoint.sh"]
